/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;


import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author isabellefredriksson
 */
public class NyregistreraUtrustning extends javax.swing.JFrame {

    private InfDB idb;
    /**
     * Creates new form NyregistreraUtrustning
     */
    public NyregistreraUtrustning(InfDB idb) {
        this.idb = idb;
        initComponents();
        
        txtKommunikation.setVisible(false);
        txtTeknik.setVisible(false);
        txtVapen.setVisible(false);
        lblKaliber.setVisible(false);
        lblKtaftkälla.setVisible(false);
        lblöverföring.setVisible(false);
        
    }

    //NyregistreraUtrustning(InfDB idb) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        lblRubrikNyUtrustning = new javax.swing.JLabel();
        lblFyllIInfo = new javax.swing.JLabel();
        lblBenämning = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();
        txtUtrustningBenämning = new javax.swing.JTextField();
        cbValdKategori = new javax.swing.JComboBox<>();
        btnNästa = new javax.swing.JButton();
        lblUtrustningID = new javax.swing.JLabel();
        lblHämtadID = new javax.swing.JLabel();
        btnHämtaID = new javax.swing.JButton();
        txtKommunikation = new javax.swing.JTextField();
        txtVapen = new javax.swing.JTextField();
        txtTeknik = new javax.swing.JTextField();
        lblöverföring = new javax.swing.JLabel();
        lblKaliber = new javax.swing.JLabel();
        lblKtaftkälla = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrikNyUtrustning.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblRubrikNyUtrustning.setText("Lägg till ny utrustning");

        lblFyllIInfo.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lblFyllIInfo.setText("Fyll i följande information:");

        lblBenämning.setText("Benämning:");

        lblKategori.setText("Kategori:");

        txtUtrustningBenämning.setColumns(10);

        cbValdKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Välj-", "Kommunikation", "Vapen", "Teknik" }));
        cbValdKategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbValdKategoriItemStateChanged(evt);
            }
        });

        btnNästa.setText("Nästa");
        btnNästa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNästaActionPerformed(evt);
            }
        });

        lblUtrustningID.setText("Utrustnings_ID:");

        btnHämtaID.setText("Hämta ID");
        btnHämtaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHämtaIDActionPerformed(evt);
            }
        });

        txtKommunikation.setColumns(10);

        txtVapen.setColumns(10);

        txtTeknik.setColumns(10);

        lblöverföring.setText("Överföringsteknik");

        lblKaliber.setText("Kaliber");

        lblKtaftkälla.setText("Kraftkälla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNästa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblRubrikNyUtrustning))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFyllIInfo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblUtrustningID)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblHämtadID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHämtaID))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblKategori)
                                                .addComponent(lblBenämning)
                                                .addComponent(lblöverföring))
                                            .addGap(38, 38, 38))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblKaliber, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblKtaftkälla, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUtrustningBenämning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbValdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtKommunikation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtVapen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTeknik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblRubrikNyUtrustning)
                .addGap(32, 32, 32)
                .addComponent(lblFyllIInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUtrustningID)
                    .addComponent(lblHämtadID)
                    .addComponent(btnHämtaID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBenämning)
                    .addComponent(txtUtrustningBenämning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKategori)
                    .addComponent(cbValdKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKommunikation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblöverföring))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVapen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKaliber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeknik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKtaftkälla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnNästa)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNästaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNästaActionPerformed
        // TODO add your handling code here:
            
        

            String kategori = cbValdKategori.getSelectedItem().toString();
            String HID = lblHämtadID.getText();
            String ID = lblHämtadID.getText();
            String Benämning = txtUtrustningBenämning.getText();
            String överföring = txtKommunikation.getText();
            String kaliber = txtVapen.getText();
            String kraft = txtTeknik.getText();
            String kommunikation = "Kommunikation";
            String vapen = "Vapen";
            String teknik = "Teknik";
            String välj = "-Välj-";
        
             if (HID.isBlank()) {
                JOptionPane.showMessageDialog(null, "Hämta ID");  
            }
         
             if (kategori.equals(välj)) {
                JOptionPane.showMessageDialog(null, "Välj Kategori");
            }

            
             if (Validering.textFaltVarde(txtUtrustningBenämning)) { 
                 
            try {

           
           if (kategori.equals(kommunikation)) {
          String kom = "INSERT INTO mibdb.Kommunikation (Utrustnings_ID, overforingsteknik) VALUES ('" + ID + "', '" + överföring + "')";
                idb.insert(kom);
                String NyUtrustning1 = "INSERT INTO mibdb.Utrustning (Utrustnings_ID, Benamning) VALUES ('" + ID + "', '" + Benämning + "')";
                idb.insert(NyUtrustning1);
            }
            
           // if (kategori.equals(vapen)) {
             //   Validering.textFaltVarde(txtVapen);
            
           if (kategori.equals(vapen)) {
                String vap = "INSERT INTO mibdb.Vapen (Utrustnings_ID, kaliber) VALUES ('" + ID + "', '" + kaliber + "')";
                idb.insert(vap);
                String NyUtrustning2 = "INSERT INTO mibdb.Utrustning (Utrustnings_ID, Benamning) VALUES ('" + ID + "', '" + Benämning + "')";
                idb.insert(NyUtrustning2);
            }
           
           // if (kategori.equals(teknik)) {
             //   Validering.textFaltVarde(txtTeknik);
            
            if (kategori.equals(teknik)) {
                String tek = "INSERT INTO mibdb.Teknik (Utrustnings_ID, Kraftkalla) VALUES ('" + ID + "', '" + kraft + "')";
                idb.insert(tek);
                String NyUtrustning3 = "INSERT INTO mibdb.Utrustning (Utrustnings_ID, Benamning) VALUES ('" + ID + "', '" + Benämning + "')";
                 idb.insert(NyUtrustning3);
                //JOptionPane.showMessageDialog(null, "Ny utrustning tillagd");
            }

            
 
        }catch (InfException e) {
            System.out.println(e.getMessage());
            }
             }
 
     
    }//GEN-LAST:event_btnNästaActionPerformed

    private void btnHämtaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHämtaIDActionPerformed
        // TODO add your handling code here:
        
            //String fråga1 = "SELECT max(Utrustnings_ID) FROM mibdb.Utrustning";
            
          try {
            String fråga = "SELECT max(Utrustnings_ID) FROM mibdb.Utrustning";
            
            String svar1 = idb.fetchSingle(fråga); 
            
            int svaret = Integer.parseInt(svar1);
            int resultat = svaret +1;
            
            String slutResultat = Integer.toString(resultat);
            
           lblHämtadID.setText(slutResultat);
            
            
        }catch (Exception e) {
            System.out.println(e.getMessage());
            }
    }//GEN-LAST:event_btnHämtaIDActionPerformed

    private void cbValdKategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbValdKategoriItemStateChanged
        // TODO add your handling code here:
        
        String vald = cbValdKategori.getSelectedItem().toString();
        
        txtKommunikation.setVisible(false);
        txtTeknik.setVisible(false);
        txtVapen.setVisible(false);
        lblKaliber.setVisible(false);
        lblKtaftkälla.setVisible(false);
        lblöverföring.setVisible(false);
        
       
        
        if(vald.equals("Kommunikation")) {
             txtKommunikation.setVisible(true);
             lblöverföring.setVisible(true);
        }
        
        if(vald.equals("Vapen")){
            txtVapen.setVisible(true);
            lblKaliber.setVisible(true);
        }
        
        if(vald.equals("Teknik")) {
             txtTeknik.setVisible(true);
             lblKtaftkälla.setVisible(true);
        }
    }//GEN-LAST:event_cbValdKategoriItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NyregistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NyregistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NyregistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NyregistreraUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHämtaID;
    private javax.swing.JButton btnNästa;
    private javax.swing.JComboBox<String> cbValdKategori;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblBenämning;
    private javax.swing.JLabel lblFyllIInfo;
    private javax.swing.JLabel lblHämtadID;
    private javax.swing.JLabel lblKaliber;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblKtaftkälla;
    private javax.swing.JLabel lblRubrikNyUtrustning;
    private javax.swing.JLabel lblUtrustningID;
    private javax.swing.JLabel lblöverföring;
    private javax.swing.JTextField txtKommunikation;
    private javax.swing.JTextField txtTeknik;
    private javax.swing.JTextField txtUtrustningBenämning;
    private javax.swing.JTextField txtVapen;
    // End of variables declaration//GEN-END:variables
}
