/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package mib;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;


/**
 *
 * @author isabellefredriksson
 */
public class SökAlienPlats extends javax.swing.JFrame {
    
    private InfDB idb;

    /** Creates new form SökOmråden */
    public SökAlienPlats(InfDB idb) {
        this.idb = idb;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrikSökOmråde = new javax.swing.JLabel();
        lblAngeOmråde = new javax.swing.JLabel();
        txtSök = new javax.swing.JTextField();
        lblResultat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultat = new javax.swing.JTextArea();
        btnSök = new javax.swing.JButton();
        txtTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrikSökOmråde.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblRubrikSökOmråde.setText("Sök efter Aliens på en plats");

        lblAngeOmråde.setText("Ange plats:");

        txtSök.setColumns(10);

        lblResultat.setText("Resultat:");

        txtResultat.setColumns(20);
        txtResultat.setRows(5);
        jScrollPane2.setViewportView(txtResultat);

        btnSök.setText("Sök");
        btnSök.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSökActionPerformed(evt);
            }
        });

        txtTillbaka.setText("Tillbaka");
        txtTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSök, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSök))
                            .addComponent(lblAngeOmråde)))
                    .addComponent(lblRubrikSökOmråde)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTillbaka)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblResultat)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblRubrikSökOmråde)
                .addGap(51, 51, 51)
                .addComponent(lblAngeOmråde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSök, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSök))
                .addGap(58, 58, 58)
                .addComponent(lblResultat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(txtTillbaka)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSökActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSökActionPerformed
        // Metoden söker fram och visar alla aliens på en angiven plats.

        txtResultat.setText("");
        String plats = txtSök.getText();

        if (Validering.textFaltVarde(txtSök)) {
            try {
                //Hämtar platsen 
                String frågaPlats = "SELECT mibdb.Plats.Benamning from mibdb.Plats where Benamning = '" + plats + "'";
                String svarPlats = idb.fetchSingle(frågaPlats);

                //Kontrollerar att platsen finns.
                if (svarPlats == null) {
                    JOptionPane.showMessageDialog(null, "Platsen finns inte");

                } else {
                    //Hämtar alla aliens på angiven plats
                    String fråga = "SELECT Namn FROM mibdb.Alien "
                            + "JOIN mibdb.Plats ON mibdb.Plats.Plats_ID = mibdb.Alien.Plats "
                            + "WHERE mibdb.Plats.Benamning = '" + plats + "'";

                    ArrayList<HashMap<String, String>> svar = idb.fetchRows(fråga);

                    for (HashMap<String, String> Namn : svar) {

                        txtResultat.append(Namn.get("Namn") + "\n"); // Skriver ut alla aliens på platsen.
                    }

                }

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        
    }//GEN-LAST:event_btnSökActionPerformed

    private void txtTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTillbakaActionPerformed
        // TODO add your handling code here:
        new AgentMenu(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_txtTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SökAlienPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SökAlienPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SökAlienPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SökAlienPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSök;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAngeOmråde;
    private javax.swing.JLabel lblResultat;
    private javax.swing.JLabel lblRubrikSökOmråde;
    private javax.swing.JTextArea txtResultat;
    private javax.swing.JTextField txtSök;
    private javax.swing.JButton txtTillbaka;
    // End of variables declaration//GEN-END:variables

}
