/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author jackmacbook
 */
public class ÄndraAlien extends javax.swing.JFrame {
    
    private InfDB idb;

    /**
     * Creates new form ÄndraAlien
     */
    public ÄndraAlien(InfDB idb) {
         this.idb = idb;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTelefon = new javax.swing.JLabel();
        lblLösenord = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RubrikNyAlien = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblRas = new javax.swing.JLabel();
        btnUppdatera = new javax.swing.JButton();
        lblAnsvarigAgent = new javax.swing.JLabel();
        lblAktuellPlats = new javax.swing.JLabel();
        lblTillbaka = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        btnÄndraNamn = new javax.swing.JButton();
        btnÄndraRegDatum = new javax.swing.JButton();
        btnÄndraLösenord = new javax.swing.JButton();
        btnÄndraTelefon = new javax.swing.JButton();
        btnÄndraPlats = new javax.swing.JButton();
        btnÄndraAgent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTelefon.setText("Telefon:");

        lblLösenord.setText("Lösenord:");

        jLabel1.setText("Registreringsdatum");

        RubrikNyAlien.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        RubrikNyAlien.setText("Ändra alien information");

        lblNamn.setText("Namn:");

        lblRas.setText("Ras:");

        btnUppdatera.setText("Ändra Ras");
        btnUppdatera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdateraActionPerformed(evt);
            }
        });

        lblAnsvarigAgent.setText("Ansvarig agent:");

        lblAktuellPlats.setText("Aktuell plats:");

        lblTillbaka.setText("Tillbaka till menyn");

        btnTillbaka.setText("Tryck här");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnÄndraNamn.setText("Ändra namn");
        btnÄndraNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraNamnActionPerformed(evt);
            }
        });

        btnÄndraRegDatum.setText("Ändra Reg.Datum");
        btnÄndraRegDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraRegDatumActionPerformed(evt);
            }
        });

        btnÄndraLösenord.setText("Ändra lösenord");
        btnÄndraLösenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraLösenordActionPerformed(evt);
            }
        });

        btnÄndraTelefon.setText("Ändra telefon");
        btnÄndraTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraTelefonActionPerformed(evt);
            }
        });

        btnÄndraPlats.setText("Ändra plats");
        btnÄndraPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraPlatsActionPerformed(evt);
            }
        });

        btnÄndraAgent.setText("Ändra agent");
        btnÄndraAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÄndraAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RubrikNyAlien)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTillbaka)
                                .addGap(28, 28, 28)
                                .addComponent(btnTillbaka))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(lblLösenord)
                                    .addComponent(lblNamn)
                                    .addComponent(lblTelefon)
                                    .addComponent(lblRas))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnÄndraRegDatum)
                                    .addComponent(btnÄndraLösenord)
                                    .addComponent(btnÄndraNamn)
                                    .addComponent(btnÄndraTelefon)
                                    .addComponent(btnÄndraPlats)
                                    .addComponent(btnÄndraAgent)
                                    .addComponent(btnUppdatera)))
                            .addComponent(lblAnsvarigAgent)
                            .addComponent(lblAktuellPlats))
                        .addGap(0, 74, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(RubrikNyAlien)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnÄndraRegDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLösenord)
                    .addComponent(btnÄndraLösenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(btnÄndraNamn))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(btnÄndraTelefon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAktuellPlats)
                    .addComponent(btnÄndraPlats))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnsvarigAgent)
                    .addComponent(btnÄndraAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRas)
                    .addComponent(btnUppdatera))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTillbaka)
                    .addComponent(btnTillbaka))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void btnUppdateraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdateraActionPerformed
        // TODO add your handling code here:
        new ÄndraAliensRas(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUppdateraActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // TODO add your handling code here:
        new AgentMenu(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnÄndraNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraNamnActionPerformed
        // TODO add your handling code here:
        new ÄndraAliensNamn(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnÄndraNamnActionPerformed

    private void btnÄndraRegDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraRegDatumActionPerformed
        // TODO add your handling code here:
        new ÄndraAliensRegDatum(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnÄndraRegDatumActionPerformed

    private void btnÄndraTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraTelefonActionPerformed
        // TODO add your handling code here:
        new ÄndraAliensTelefon(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnÄndraTelefonActionPerformed

    private void btnÄndraPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraPlatsActionPerformed
        // TODO add your handling code here:
        new ÄndraAliensPlats(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnÄndraPlatsActionPerformed

    private void btnÄndraAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraAgentActionPerformed
        // TODO add your handling code here:
        new ÄndraAliensAsvarigaAgent(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnÄndraAgentActionPerformed

    private void btnÄndraLösenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÄndraLösenordActionPerformed
        // TODO add your handling code here:
        new ÄndraAlienLösenord(idb).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnÄndraLösenordActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ÄndraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ÄndraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ÄndraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ÄndraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RubrikNyAlien;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnUppdatera;
    private javax.swing.JButton btnÄndraAgent;
    private javax.swing.JButton btnÄndraLösenord;
    private javax.swing.JButton btnÄndraNamn;
    private javax.swing.JButton btnÄndraPlats;
    private javax.swing.JButton btnÄndraRegDatum;
    private javax.swing.JButton btnÄndraTelefon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAktuellPlats;
    private javax.swing.JLabel lblAnsvarigAgent;
    private javax.swing.JLabel lblLösenord;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblRas;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblTillbaka;
    // End of variables declaration//GEN-END:variables
}
